### ISSUE TITLE
模型通过hf-mirror下载的时候需要用户名密码?

### ISSUE THREAD

**Issue by zhanghui-china** [aJupyter/EmoLLM#15]
<img width="1267" alt="b374f53db8d19b508e9afd2fa12c5d7" src="https://github.com/aJupyter/EmoLLM/assets/63148804/63b15cd2-0d9f-4c81-afb6-96d282ae704c">

下载的脚本如下：
`import os

# 设置环境变量
os.environ['HF_ENDPOINT'] = 'https://hf-mirror.com'

# 下载模型
os.system('huggingface-cli download --resume-download jujimeizuo/EmoLLM_Model  --local-dir-use-symlinks False --local-dir /home/zhanghui/models/EmoLLM')`

是不是模型还不是公开模型？

**Comment by zhanghui-china** [comment]
原来模型从openxlab下载的。抱歉没看清楚。。。

**Comment by aJupyter** [comment]
你好，欢迎关注EmoLLM，我们并没有将模型传到huggingface
可以在下面的平台下载：
1. https://www.modelscope.cn/models/aJupyter/EmoLLM/
2. https://openxlab.org.cn/models/detail/jujimeizuo/EmoLLM_Model
